### PR TITLE
Added Date & Time to the log with the ability to disable it

### PR DESCRIPTION
**Pull request by TheClonker**
I'm not sure you like my coding style ^^

I added the boolean logger.options.disableprintDate to disable the logging of Time & Date

### CODE REVIEW

**Comment by AljoschaMeyer** [comment]
Now that I looked at the module again, I'm not sure whether date logging actually belongs in it.

What you wrote can easily be accomplished via the `preformat` option, see the [simple example](https://github.com/AljoschaMeyer/vorpal-log/blob/master/examples/simpleDemo.coffee). Instead of rendering markdown, the preformat function would simply put the date in front of the message.

Having this built in would be convenient, but maybe out of place? At the very least, options modifying the behavior of the default loggers should be kept separate from the other options.

Since you actually needed the feature, what's your opinion on this? Did you decide against using the `preformat` function, or were you unaware of it?

**Comment by TheClonker** [comment]
I did not use the `preformat` function because it outputs after the "[info]" etc. Tag and i wanted the time before that. 

What do you think about something like this `"prefixFuntion() #{chalk.dim '[debug]'} #{msg} suffixFuntion()"` that the user could define as logger.options.prefixFuntion ?

**Comment by AljoschaMeyer** [comment]
Changed date logging to be disabled by default, pass `printDate` as an option to enable it. Also updated the readme.

**Comment by AljoschaMeyer** [comment]
Published as 1.1.0

**Pull request merged**
